name: dart_settings_page_w_paper_elements
description: A sample Polymer application
dependencies:
  paper_elements: any
  polymer: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/dart_settings_page_w_paper_elements.html
